name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
      echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
      docker build -f Dockerfile -t reneh98/demo:latest ./
      GIT_SHA="$(git rev-parse --short HEAD"
      docker tag reneh98/demo:latest reneh98/demo:$GIT_SHA

